### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ulugbekov** [rails3book/ticketee#1]
Hi,
I just bought the book. Rails 3 in action.
When I did   rails g cucumber:install

files under features/support/      are missing.
Only env.rb is available.
files under features/step_definitions/  are also missing.
Am I missing something.
thanks

**Comment by radar** [comment]
Hello,

Thanks for buying the book!

The latest version of cucumber-rails breaks the book at the moment. In hindsight, it was silly to _not_ specify a version for `cucumber-rails` within the project. [This thread](http://www.manning-sandbox.com/forum.jspa?forumID=541) discusses the problem also. There's a fix there for your issue (set version of cucumber-rails to 1.0.6 and run `bundle update cucumber-rails`).

If you have any other issues, please post them to the [Rails 3 in Action forum](http://www.manning-sandbox.com/forum.jspa?forumID=541&start=0) as that is the canonical place to discuss them.

Thanks again for reading!
